[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning"
log_cli = true
addopts = ["--import-mode=importlib"]
pythonpath = ["src"]
testpaths = ["tests"]
[tool.hatch.version]
source = "code"
path = "src/averagewatts/__init__.py"
